services:
  nest-api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_OUTPUT=${LOG_OUTPUT}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    profiles:
      - prod
