services:
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - LOG_OUTPUT=${LOG_OUTPUT}
    volumes:
      - .:/app
      - nest_api_node_modules:/app/node_modules
    command: yarn start:dev
    ports:
      - '3000:3000'
    restart: unless-stopped
    profiles:
      - dev

  nest-api-prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - '3001:3000'
    restart: unless-stopped
    profiles:
      - prod

  nest-api-test:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app:delegated
      - npm-cache:/root/.npm
    command: >
      sh -c "if [ ! -d node_modules ]; then npm ci; fi &&
             npm run test && npm run test:e2e"


volumes:
  npm-cache:
  nest_api_node_modules:
