FROM node:22-alpine

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

# Usa o ambiente de testes como base
ENV NODE_ENV=test

# Rodar testes ao iniciar o container
CMD ["sh", "-c", "yarn test && yarn test:cov && yarn test:e2e"]
