services:
  nest-api:
    command: yarn start:dev
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - LOG_OUTPUT=${LOG_OUTPUT}
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev
