FROM node:22-alpine AS deps
WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:22-alpine AS test
WORKDIR /app
ENV NODE_ENV=test

COPY --from=deps /app/node_modules ./node_modules

COPY . .

# Roda os testes
CMD ["sh", "-c", "yarn test && yarn test:e2e"]
